---
#####################################################################
# This play execute a bunch of different lookups

- hosts: localhost
  gather_facts: false
  vars_files:
    - vars/sample.yml

  tasks:

    - name: Test flattened lookup
      debug:
        msg: "Flattened {{myDic.simple}} ... {{ lookup('flattened', myDic.simple) }}"

    - name: Test dict lookup
      debug:
        msg: "Dict {{myDic.simple}} .. {{ lookup('dict', myDic.simple) }}"

    - name: Test items lookup
      debug:
        msg: "item.name {{ item.name }} ... item.uid {{ item.uid }} ... item.groups {{ item.groups }}"
      with_items:
        - { name: testuser1, uid: 1002, groups: "wheel, staff" }
        - { name: testuser2, uid: 1003, groups: staff }

    - name: Test nested lookup
      debug:
        msg: "item0 {{item[0]}} ... item1 {{item[1]}}"
      with_nested:
        - ['usr1','user2']
        - ['db1','db2','db3']

    - name: Test cartesian lookup
      debug:
        msg: "item0 {{item[0]}} ... item1 {{item[1]}}"
      with_cartesian:
        - ['usr1','user2']
        - ['db1','db2','db3']

    - name: Test subelements lookup
      debug:
        # msg: "Subelemente of {{myDic}} ... {{item}}"
        var: item
      with_subelements:
        - "{{myDic.users}}"
        - auth

    - name: Test together lookup
      debug:
        msg: "item {{item}}"
      with_together:
        - ['a','b','c','d']
        - [1,2,3]

    - name: Test contains test
      debug:
        #msg: "{{ (myDic.lacp_groups|selectattr('interfaces', 'contains', 'em1')|first).master }}"
        var: myDic.lacp_groups|selectattr('interfaces', 'contains', 'em1')|list

