---
#####################################################################
# This play will read variables from vault file
# Run ansible-playbook with --ask-vault-pass or --vault-password-file
# Vault password: 123

- name: Accessing Vault in Playbooks
  hosts: localhost
  vars_files: vault.txt

  tasks:

    - name: Show secret1 value
      debug:
        msg: "{{ secret1 }}"

