---
## call ansible-playbook with --ask-vault-pass parameter or --vault-password-file

- name: Accessing Vaults in Playbooks
  hosts: all
  vars_files: vault.txt
  tasks:
    - name: Show secret1 value
      debug:
        msg: "{{ secret1 }}"

    # Testing ansible_user and ansible_password in vault file
    - name: Test command
      command: date
      register: date

    - name: Debug
      debug:
        msg: "{{date.stdout}}"
